import mongoose from 'mongoose';
// should be generated by Aggregation pipeline
const leaderboardSchema = mongoose.Schema({
    mockTestId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'MockTest',
        required:true
    },
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    score:{
        type:Number,
        default:0,
        required:true
    },
    percentile:{
        type:Number,
        default:0,
        required:true
    },
    rank:{
        type:Number,
        default:0,
        required:true
    },
    attemptDate:{
        type:Date
    },

});